{% set name = "colorhash" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/colorhash-{{ version }}.tar.gz
  sha256: 143d739adeeb4949d69d35274f9a973fdd5f3a77c8658be2e23f967688869c7b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - python >=3.6,<4.0

test:
  imports:
    - colorhash
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dimostenis/color-hash-python
  summary: Generate color based on any object
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - shaharh9110
